Feature/homework 5 UI components
AlekseyMakarov/MtsTetaAndroid pull request #3
Opened 2021-07-28 20:02 UTC by AlekseyMakarov

2021-08-02 22:12 UTC, maxlord requested changes

2021-08-02 22:12 UTC, maxlord commented on app/src/main/java/com/example/mtstetaandroid/ui/home/HomeFragment.kt
> +        recyclerMovie.addItemDecoration(object : RecyclerView.ItemDecoration() {
И лучше вынести Decoration в отдельный файл

2021-08-02 22:12 UTC, maxlord commented on app/src/main/java/com/example/mtstetaandroid/ui/movieDetails/DetailsFragment.kt
> +            ?.toBitmap(context.dpToPx(15F), context.dpToPx(15F))
Хард-код (15F). А что мешает это брать из dimens.xml? Если есть возможность, лучше придерживаться сетке дименов: 4, 8, 12, 16 и т.д.

2021-08-02 22:12 UTC, maxlord commented on app/src/main/java/com/example/mtstetaandroid/ui/movieDetails/DetailsFragment.kt
> +        val root = inflater.inflate(R.layout.fragment_details, container, false)
В этом методе ты должен только создать корневую вьюху.
Все остальные манипуляции надо производить в методе onViewCreated

2021-08-02 22:12 UTC, maxlord commented on app/src/main/java/com/example/mtstetaandroid/ui/movieDetails/DetailsFragment.kt
> +            args.putString("movie_title", movie.title)
Название аргументов лучше выносить в константы.
Да и вообще нужно применять принцип DRY (don't repeat yourself). Т.е. если литерал (строка) используется больше одного раза в коде, то ее надо выносить в константу и юзать константу.

2021-08-02 22:12 UTC, maxlord commented on app/src/main/res/layout/fragment_user.xml
> +        android:id="@+id/text_user"
id-шники вьюх нужно называть в camelCase

2021-08-02 22:12 UTC, maxlord commented on app/src/main/res/layout/movie_item.xml
> +    android:layout_width="match_parent"
Аттрибуты надо отсортировать.

2021-08-02 22:12 UTC, maxlord commented on app/src/main/res/layout/movie_item.xml
> +            android:textSize="14sp"
Все хард-коды из разметки надо вынести в dimens.xml

2021-08-03 20:54 UTC, AlekseyMakarov commented on app/src/main/res/layout/movie_item.xml
> +            android:textSize="14sp"
Хард-кодов действительно очень много,  но тут скорее вопросы к дизайнерам, которые верстали макет в фигме... И так получилось, что почти у каждой вьюхи свои отступы, размеры и т.д. Поэтому выносить это все dimens очень затратно по времени. предлагаю пока оставить как есть, и вернуться к этому позже

2021-08-10 10:22 UTC, maxlord requested changes

2021-08-10 10:22 UTC, maxlord commented on app/src/main/res/layout/fragment_details.xml
> +            </androidx.recyclerview.widget.RecyclerView>
Убери закоменченный код

2021-08-10 20:06 UTC, merged